services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Admin123
    ports:
      - 5432:5432
    volumes:
      - E:/database/postgres/data:/var/lib/postgresql/data
    
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Admin123
    ports:
      - 27017:27017
    volumes:
      - E:/database/mongodb/data:/data/db