apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_URLS: http://+:80;http://+:7777
  RabbitMq__Host: rabbit-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: Admin123
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip;User Id=postgres;Password=Admin123;Database=auctions
  IdentityServiceUrl: http://identity-svc
  Kestrel__Endpoints__Grpc__Protocols: Http2
  Kestrel__Endpoints__Grpc__Url: http://+:7777
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: http://+:80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMQ__Host: rabbit-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: Admin123
  ConnectionStrings__MongoDbConnection: mongodb://admin:Admin123@mongo-clusterip
  AuctionServiceUrl: http://auction-clusterip

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bid-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMQ__Host: rabbit-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: Admin123
  ConnectionStrings__BidDbConnection: mongodb://admin:Admin123@mongo-clusterip
  IdentityServiceUrl: http://identity-clusterip
  GrpcAuction: http://auction-clusterip:7777

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMQ__Host: rabbit-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: Admin123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  ClientApp: https://app.carsties.local
  IdentityServiceUrl: http://identity-clusterip

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  IssuerUri: https://id.carsties.local
  ClientApp: https://app.carsties.local
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip;User Id=postgres;Password=Admin123;Database=identity

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-svc-config
data:
  AUTH_SECRET: "iILdHeV2pHFmKkEFheGGNfkpqwdM7X+rXKU5zaWbmNo=" 
  AUTH_URL: https://app.carsties.local
  AUTH_URL_INTERNAL: http://webapp-clusterip:3000
  API_URL: http://gateway-clusterip/
  ID_URL: https://id.carsties.local
  ID_URL_INTERNAL: http://identity-clusterip
  NOTIFY_URL: https://api.carsties.local/notifications
