name: Build and publish

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      continue: "false"

    strategy:
      matrix:
        service:
          - name: "tahoanghai744/auction-svc"
            path: "src/AuctionService"
          - name: "tahoanghai744/search-svc"
            path: "src/SearchService"
          - name: "tahoanghai744/bid-svc"
            path: "src/BiddingService"
          - name: "tahoanghai744/identity-svc"
            path: "src/IdentityService"
          - name: "tahoanghai744/gateway-svc"
            path: "src/GatewayService"
          - name: "tahoanghai744/notify-svc"
            path: "src/NotificationService"
          - name: "tahoanghai744/web-app"
            path: "frontend/web-app"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{matrix.service.path}}/Dockerfile
          push: true
          tags: ${{matrix.service.name}}:latest
